### ISSUE TITLE
Support different failure levels, similar to the Gradle IntelliJ Plugin

### ISSUE THREAD

**Issue by peterlin741** [ChrisCarini/intellij-platform-plugin-verifier-action#11] opened 2020-11-02 22:49 UTC
By default, this action passes and the status on Github is displayed as successful if the report is successfully generated. It would be great to add support for different levels of failures.

Slack reference: https://jetbrains-platform.slack.com/archives/C012S7PA8CQ/p1604356021010900

The Gradle IntelliJ Plugin, supports a `failingLevel` property that allows you to fail the task by explicitly specifying the level of failure, which can be added as an input in the yaml file.

https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl

Possible levels: https://github.com/JetBrains/gradle-intellij-plugin/blob/ea5eb75548af4b368f2bd981d8c2d338edb3208d/src/main/groovy/org/jetbrains/intellij/tasks/RunPluginVerifierTask.groovy#L29

```
    static enum FailureLevel {
        COMPATIBILITY_WARNINGS("Compatibility warnings"),
        COMPATIBILITY_PROBLEMS("Compatibility problems"),
        DEPRECATED_API_USAGES("Deprecated API usages"),
        EXPERIMENTAL_API_USAGES("Experimental API usages"),
        INTERNAL_API_USAGES("Internal API usages"),
        OVERRIDE_ONLY_API_USAGES("Override-only API usages"),
        NON_EXTENDABLE_API_USAGES("Non-extendable API usages"),
        PLUGIN_STRUCTURE_WARNINGS("Plugin structure warnings"),
        MISSING_DEPENDENCIES("Missing dependencies"),
        INVALID_PLUGIN("The following files specified for the verification are not valid plugins"),
        NOT_DYNAMIC("Plugin cannot be loaded/unloaded without IDE restart");
```

**Comment by ChrisCarini** [comment] 2020-11-03 06:48
Hi @peterlin741 - as mentioned in the Slack thread (the one you linked above), would you mind sharing an execution that showed as passed when it should have failed?

Thank you for opening this issue! Hopefully we can get to the bottom of the root cause and make the needed improvements!

**Comment by peterlin741** [comment] 2020-11-03 18:34
Hi Chris, I can't share any specific logs, since this is proprietary code, but I can give you more background.

IntelliJ `2020.2` refactored and introduced several new libraries, which were incompatible with versions beforehand. I downloaded the [IntelliJ Plugin Verifier](https://github.com/JetBrains/intellij-plugin-verifier) JAR directly and ran the `2020.2-EAP` compatible version of my plugin against the following:

- Against IntelliJ `2020.2`, where the report generated warnings, but still displayed a green square, indicating success

![image](https://user-images.githubusercontent.com/58699538/98026173-b7e03e00-1dd8-11eb-9c56-6b94d9357f7d.png)

- Against IntelliJ `2019.3`, where the report failed due to compatibility issues, and displayed a red square

![image](https://user-images.githubusercontent.com/58699538/98026277-df370b00-1dd8-11eb-94c7-c1dc309489e5.png)

- Running my `2020.2` compatible plugin branch against `2019.3` should fail, but the status is displayed as passing in the github action status

![image](https://user-images.githubusercontent.com/58699538/98026476-2d4c0e80-1dd9-11eb-9da8-7d92a14f310c.png)

**Comment by ChrisCarini** [comment] 2020-11-04 06:49
Hi @peterlin741 - thank you for digging in and figuring this out! You provided the information I was hoping to see from the logs (I didn't want bulk logs, just specific to this GH action, which shouldn't be printing any proprietary things afaik).

From the sounds of it, this could easily be fixed by removing the `$` from the regex, correct? I'm almost wondering if it makes sense to (a) do this quick fix, or (b) hold off for some overall improvements on the errors checked (based on what you provided), or, (c) a combination of both (a) and (b). Let me know your thoughts, I'm happy with any of the options.

**Comment by peterlin741** [comment] 2020-11-04 09:01
hi @ChrisCarini, no problem! That's correct, removing the`$` from the regex should fix it. I think (c) a combination of the above is probably best. Mainly because if this is broken for me, it is probably currently broken for most users using the latest version of the IntelliJ Plugin Verifier, specifically checking for compatibility issues. If users are using the plugin verifier, their project is most likely older and also has other warnings, breaking the regex.

I haven't looked too closely at the implementation details/changes required, but I think in the long term, it'll definitely be easier in terms of maintainability for you to follow the enum class in the source code, since new versions of the `IntelliJ Plugin Verifier` may change the output format, causing breaking changes, and require additional debugging.

**Comment by ChrisCarini** [comment] 2020-11-06 10:14
Hey @peterlin741 - thank you for PR #12 for the quick fix!

I just ran two executions on a sample plugin of mine that is in a known failure state right now; both showed failures as expected.

Would you mind also doing a test, since my failure does not have extra characters that the removal of the `$` would catch? You can do this by temporarily changing the workflow file to below:
```
uses: ChrisCarini/intellij-platform-plugin-verifier-action@d3de73c8c612421670001960de64e97916093571
```

Once you report back that it's fixed for you, I'll go ahead and release a new version of the action (and update the `latest` tag as well).

Thank you again! Really appreciate the contribution (and, of course, raising this issue)!

**Comment by peterlin741** [comment] 2020-11-06 22:27
hi @ChrisCarini, everything looks good on my end!

Testing Notes:
- IntelliJ `2020.2` refactored several libraries, which were incompatible with previous versions beforehand.
- Tested a `2020.2` compatible version of my plugin, which should only work with `IntelliJ 2020.2` and `IntelliJ EAP`
- Tested a `2019.3` compatible version of my plugin, which should only work with  `IntelliJ 2019.3` and `IntelliJ 2020.1`
- I tested both the community and ultimate editions 

**Test 1**
- Running a `2020.2` compatible plugin against `2020.2` and `EAP` succeeds as expected. I do not see any compatibility issues in the logs.

![image](https://user-images.githubusercontent.com/58699538/98420205-ac00b000-2054-11eb-992d-415e9d12f86b.png)

![image](https://user-images.githubusercontent.com/58699538/98420046-59bf8f00-2054-11eb-9631-31bcf5c1ab33.png)

----------
**Test 2**
- Running a `2020.2` compatible plugin against `2019.3` and `2020.1` fails as expected. I see the expected failure statement in the logs:
```
Plugin com.google.gct.core:20.12.1-SNAPSHOT against IC-193.5233.102: 21 compatibility problems, some of which may be caused by missing optional dependencies. 66 usages of deprecated API. 4 usages of experimental API. 1 usage of internal API
```
![image](https://user-images.githubusercontent.com/58699538/98419819-daca5680-2053-11eb-866e-450a20a090d7.png)

![image](https://user-images.githubusercontent.com/58699538/98420106-6e9c2280-2054-11eb-89c5-2cb34b8d30d7.png)

----------
**Test 3**
- Running a `2019.3` compatible plugin against `2019.3` and `2020.1` succeeds as expected. I do not see any compatibility issues in the logs.

![image](https://user-images.githubusercontent.com/58699538/98419842-e9187280-2053-11eb-92f6-32630c9b682c.png)

- yaml IDE versions same as screenshot in Test 2

----------
**Test 4**
- Running a `2019.3` compatible plugin against `2020.2` and `EAP` fails as expected. I see the expected failure statement in the logs:

```
Plugin com.google.gct.core:20.12.1-SNAPSHOT against IU-202.6397.94: 19 compatibility problems. 5 usages of scheduled for removal API and 147 usages of deprecated API. 4 usages of experimental API. 2 usages of internal API
```

![image](https://user-images.githubusercontent.com/58699538/98420254-ca66ab80-2054-11eb-9397-bbc8eae8c5d7.png)

- yaml IDE versions same as screenshot in Test 1

**Comment by ChrisCarini** [comment] 2020-11-06 23:03
Great! Thank you again for the detail @peterlin741 ! I've just released [v1.0.4](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/releases/tag/v1.0.4) with your change, and also moved the [latest](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/releases/tag/latest) tag to point to this version/commit as well!

I'm going to leave this issue open, and the remaining work to be accomplished for this issue is to get the remaining strings added into the action.

**Comment by peterlin741** [comment] 2020-11-07 00:53
thanks @ChrisCarini! Don't forget to update the sample docs on the [homepage](https://github.com/marketplace/actions/intellij-platform-plugin-verifier) to `v1.0.4`

**Comment by ChrisCarini** [comment] 2020-11-07 02:48
@peterlin741 - Nice catch! I totally forgot to do that! I just updated the `README.md` (where the sample docs are pulled from) and just changed everything to reference the `latest` tag. Figure that way I won't have to make future-updates to the `README.md` when new versions are released.

**Closed** 2021-01-24 06:15 UTC

**Comment by ChrisCarini** [comment] 2023-09-21 22:21
@all-contributors please add @peterlin741 for bug, idea, userTesting
